# Routes

# CMS routes
- route: /
  maps:
    controller: authentication
    action    : login

- route: /:controller
  maps:
    controller: *
    action    : index

- route: /:controller/:action
  maps:
    controller: *
    action    : *

- route: /:controller/page/:page/sort/:sort/order/:order
  maps:
    controller: *
    action    : index
    page      : *
    sort      : *
    order     : *

- route: /:controller/page/:page
  maps:
    controller: *
    action    : index
    page      : *

- route: /:controller/:action/page/:page
  maps:
    controller: *
    action    : *
    page      : *

- route: /:controller/:action/:id
  maps:
    controller: *
    action    : *
    id        : *